<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <Version>1.4.0</Version>
    <Authors>Julien Creach</Authors>
    <PackageTags>DI, ServiceProvider, Attribute</PackageTags>
    <Description>This library provide tools to facilitate dependency injection when using dotnet.</Description>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/jcreach/MeleagantDependencyScan.git</RepositoryUrl>
    <PackageReleaseNotes>Add dotnet 10 and 9 version support</PackageReleaseNotes>
    <Copyright>$(Authors)</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

</Project>
